### ISSUE TITLE
Question: How can I access the custom_fields attribute of the account created?

### ISSUE THREAD

**Issue by cangulo** [hashicorp/learn-terraform-aft-account-customizations#1]
Hi there, 
first of all thanks for this repo, is really a good example of how to take advantage of AFT.  

Considering that the account request defined in the _learn-terraform-aft-account-request_ repo has the `custom_fields` attribute and the [documentation](learn-terraform-aft-account-request)  refers that it as metadata we can use in the account customizations or provisioning configuration. How can we get that parameter when executing the account-customization flow? 

Thanks!
Regard,
Carlos Angulo.

**Comment by imknysh** [comment]
I have the same question. Does someone have an answer?

**Comment by imknysh** [comment]
There is some information regarding this [https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/34](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/34)

**Comment by cangulo** [comment]
After release 1.3.3 (at least is when I noticed it)

The `custom_fields` provided in the [account request repo](https://github.com/hashicorp/learn-terraform-aft-account-request) are stored as ssm parameters in the target account as:

/aft/account-request/custom-fields/`CUSTOM_FIELD_NAME`


Reference:
https://learn.hashicorp.com/tutorials/terraform/aws-control-tower-aft

**Comment by jmstone617** [comment]
What about for accounts created before release 1.3.3 -- is there any way to have those SSM parameters created? Do they get created on subsequent runs of the account request repo?

**Comment by drAlberT** [comment]
> /aft/account-request/custom-fields/

I can't find this information in the linked reference doc ...

Maybe the right link nowadays is: https://aws.amazon.com/blogs/mt/deploy-and-customize-aws-accounts-using-account-factory-for-terraform-in-aws-control-tower/
